### ISSUE TITLE
Issues with bash scripts/build_paddle_backend.sh

### ISSUE THREAD

**Issue by delonleo** [triton-inference-server/paddlepaddle_backend#11]
HI, I got this error when `bash scripts/build_paddle_backend.sh` ? Is it possible to fix this issues ? 

```text
/workspace/paddle_backend/src/paddle.cc: In member function 'void ModelImpl::CollectShapeRun(paddle_infer::Predictor*, const std::map<std::__cxx11::basic_string<char>, std::vector<int> >&)':
/workspace/paddle_backend/src/paddle.cc:79:32: error: 'class paddle_infer::Predictor' has no member named 'GetInputType'; did you mean 'GetInputNames'?
   79 |   auto input_type = predictor->GetInputType();
      |                                ^~~~~~~~~~~~
      |                                GetInputNames
make[2]: *** [CMakeFiles/triton-paddle-backend.dir/build.make:82: CMakeFiles/triton-paddle-backend.dir/src/paddle.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:166: CMakeFiles/triton-paddle-backend.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

**Comment by heliqi** [comment]
This issue has been fixed. 
Please pull the latest Paddle-Backend code and  use 'develop' PaddlePaddle.

**Comment by delonleo** [comment]
hi @heliqi, thanks for the prompt reply. How do we use develop PaddlePaddle ?

**Comment by heliqi** [comment]
@delonleo 
There are two ways:
1. You can use this docker images:  paddlepaddle/triton_paddle:21.10
2. Based on this [dockerfile](https://github.com/triton-inference-server/paddlepaddle_backend/blob/main/paddle-lib/Dockerfile),  modify this line of code(https://github.com/triton-inference-server/paddlepaddle_backend/blob/6c1c935e9978f5606082cfb372cc74948bcb6e7a/paddle-lib/Dockerfile#L48):
`release 2.3` to `develop`.

Removing the `git checkout release /2.3` code will also work.
