### ISSUE TITLE
Which script is the source code for loading the model?

### ISSUE THREAD

**Issue by qiu-pinggaizi** [triton-inference-server/paddlepaddle_backend#15]
Which script is the source code for loading the model? 
I want to modify the model for encryption, so I need to add decryption to the model load, but I can't find out how the model is loaded in. @ZeyuChen @jeng1220

**Comment by heliqi** [comment]
@qiu-pinggaizi 
[Set Model Path](https://github.com/triton-inference-server/paddlepaddle_backend/blob/6c1c935e9978f5606082cfb372cc74948bcb6e7a/src/paddle.cc#L150)

[Create Paddle Predictor Instance](https://github.com/triton-inference-server/paddlepaddle_backend/blob/6c1c935e9978f5606082cfb372cc74948bcb6e7a/src/paddle.cc#L209)

If you use decryption, you may need to do this:
1. read model before Set Model Path
2. decryption the model string
3. Use `analysis_config_->SetModelBuffer`  interface. 
   `analysis_config_->SetModel`  Interface  is only used to set the model path and cannot be used to set the model string(or model buffer).
```
void SetModelBuffer(const char* model_buffer, size_t model_buffer_size,
                    const char* params_buffer, size_t params_buffer_size);
```

**Comment by qiu-pinggaizi** [comment]
ok, thanks @heliqi
