### ISSUE TITLE
error when building paddle backend

### ISSUE THREAD

**Issue by hientq-1908** [triton-inference-server/paddlepaddle_backend#16]
> /workspace/paddle_backend/src/paddle.cc:78:32: error: 'class paddle_infer::Predictor' has no member named 'GetInputTypes'; did you mean 'GetInputNames'?
   78 |   auto input_type = predictor->GetInputTypes();
      |                                ^~~~~~~~~~~~~
      |                                GetInputNames
/workspace/paddle_backend/src/paddle.cc: In constructor 'ModelImpl::ModelImpl(const char*, const char*, TRITONPADDLE_Config*, int32_t, cudaStream_t)':
/workspace/paddle_backend/src/paddle.cc:177:23: error: 'struct paddle::AnalysisConfig' has no member named 'SetExecStream'
  177 |     analysis_config_->SetExecStream((void*)stream);
      |                       ^~~~~~~~~~~~~
/workspace/paddle_backend/src/paddle.cc:198:27: error: 'struct paddle::AnalysisConfig' has no member named 'EnableVarseqlen'
  198 |         analysis_config_->EnableVarseqlen();
      |                           ^~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/triton-paddle-backend.dir/build.make:82: CMakeFiles/triton-paddle-backend.dir/src/paddle.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:166: CMakeFiles/triton-paddle-backend.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

Can anyone give me an idea how to fix this?

**Comment by heliqi** [comment]
To compile Paddle Backend, please use Paddle version 2.4 or later.

If you compile paddle backend with instructions similar to the following, the Paddle version of the `PADDLE_INFERENCE_DIR` must be no less than 2.4.
```
cmake .. -DPADDLE_INFERENCE_DIR=../paddle-lib/paddle -DTRITON_COMMON_REPO_TAG=r21.10 -DTRITON_CORE_REPO_TAG=r21.10 -DTRITON_BACKEND_REPO_TAG=r21.10
```

**Comment by hientq-1908** [comment]
> To compile Paddle Backend, please use Paddle version 2.4 or later.
> 
> If you compile paddle backend with instructions similar to the following, the Paddle version of the `PADDLE_INFERENCE_DIR` must be no less than 2.4.
> 
> ```
> cmake .. -DPADDLE_INFERENCE_DIR=../paddle-lib/paddle -DTRITON_COMMON_REPO_TAG=r21.10 -DTRITON_CORE_REPO_TAG=r21.10 -DTRITON_BACKEND_REPO_TAG=r21.10
> ```

thank you

**Comment by hientq-1908** [comment]
thnk
