### ISSUE TITLE
Integrate the paddle backend to the original triton server

### ISSUE THREAD

**Issue by Aun0124** [triton-inference-server/paddlepaddle_backend#2]
Is there any documentation or ways that I can configure this paddle backend and use it it the triton server together with the original backend - pytorch, tensorflow, onnyx ?

Full describe as below if i want to add the paddle backend to tritonserver:21.02-py3

run dockerfile as below:
FROM nvcr.io/nvidia/tritonserver:21.02-py3 as full
COPY ./paddlepaddle_backend/paddle-lib/paddle /opt/tritonserver/backends/paddle

docker build tritonserver_custom .

after done and i run:
docker run --gpus all --rm -p8000:8000 -p8001:8001 -p8002:8002 -v ./model-repo:/model tritonserver_custom tritonserver --model-repository=/models --model-control-mode=POLL

I get error :
I0722 06:20:09.185171 1 server.cc:217] No server context available. Exiting immediately.
error: creating server: Internal - failed to stat file /models

Any solution on this ?

**Comment by jeng1220** [comment]
@deadeyegoodwin, @dzier,
Do we have a simple example to demonstrate how to **use** multiple, different backends to infer models?

**Comment by TANKIANAUN** [comment]
Full describe as below if i want to add the paddle backend to tritonserver:21.02-py3
1)  run dockerfile as below:
FROM nvcr.io/nvidia/tritonserver:21.02-py3 as full
COPY ./paddlepaddle_backend/paddle-lib/paddle /opt/tritonserver/backends/paddle

2) docker build tritonserver_custom .

3) after done and i run:
docker run --gpus all --rm -p8000:8000 -p8001:8001 -p8002:8002 -v ./model-repo:/model tritonserver_custom tritonserver --model-repository=/models --model-control-mode=POLL 

I get error :
I0722 06:20:09.185171 1 server.cc:217] No server context available. Exiting immediately.
error: creating server: Internal - failed to stat file /models

Any solution on this ?

**Comment by zlsh80826** [comment]
Hello @TANKIANAUN,

Please refer [this Dockerfile](https://github.com/triton-inference-server/paddlepaddle_backend/blob/main/Dockerfile) for using paddle backend. You should copy ``libtriton_paddle.so`` into ``/opt/tritonserver/backends`` instead of copying ``paddle-lib``.

Following is an example Dockerfile for you to add paddle backend into tritonserver image (which include other backends). You can override [default Dockerfile](https://github.com/triton-inference-server/paddlepaddle_backend/blob/main/Dockerfile) with the following example.
```
FROM nvcr.io/nvidia/tritonserver:21.04-py3 as full

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt update \
    && apt install -y --no-install-recommends libre2-5 libb64-0d

COPY paddle-lib/paddle /opt/paddle
COPY build/libtriton_paddle.so /opt/tritonserver/backends/paddle/

ENV LD_LIBRARY_PATH="/opt/paddle/lib:$LD_LIBRARY_PATH"
```

**Comment by Aun0124** [comment]
![image](https://user-images.githubusercontent.com/44689330/126728783-85e8968f-3dc1-42e6-9692-61167918f9a3.png)

@zlsh80826 
Seems like the paddle doesn't load into the triton

docker run --gpus all --rm -p8000:8000 -p8001:8001 -p8002:8002 -v ./model-repo:/models tritonserver_custom:latest tritonserver --model-repository=/models --model-control-mode=POLL

I'm using 21.02 triton and have "$build -t tritonserver_custom ." with the dockerfile, is there any specific i need to run it to have the backend loaded?

I also try with 21.04 version and the paddle backend seems didn't load into the triton

**Comment by jeng1220** [comment]
@TANKIANAUN,
Did you see any warning/error message?
It seems an usage issue.
We need more information to know what happened.

**Comment by Aun0124** [comment]
@jeng1220 
I sucessfully run the new created tritonserver_custom without any errors, just that the paddle backend doesn't loaded into the triton. Perhaps you can try a simple demo on it and added to the readme.

**Comment by jeng1220** [comment]
@TANKIANAUN,
We already provide two simple examples - ERNIE/ResNet50 in this repository.
If you follow the https://github.com/triton-inference-server/paddlepaddle_backend/blob/main/README.md step by step, can you successfully run the examples?

**Comment by Aun0124** [comment]
@jeng1220  
yeah i can run those examples. Now I'm trying to merge this backend with the tritonserver and run it as written in the server repo just with  "docker run --gpus all --rm -p8000:8000 -p8001:8001 -p8002:8002 -v ./model-repo:/models tritonserver_custom:latest tritonserver --model-repository=/models --model-control-mode=POLL"  so i can also use other backends.

**Comment by zlsh80826** [comment]
@TANKIANAUN Did you try my comment? I can load paddle with other backends. [Custom Backend](https://github.com/triton-inference-server/server/blob/main/docs/compose.md) usage is written here, beside copying `libtriton_paddle.so` to `/opt/tritonserver/backends/paddle/`, you should also copy `paddle lib` into container and **setup the LD_LIBRARY_PATH**. The most simple way to do this is to replace [Dockerfile](https://github.com/triton-inference-server/paddlepaddle_backend/blob/main/Dockerfile) with the following code and then follow the [README](https://github.com/triton-inference-server/paddlepaddle_backend/blob/main/README.md) steps by steps to launch the demo, then you will get an image with paddlepaddle_backend and other default triton backends.
```
FROM nvcr.io/nvidia/tritonserver:21.04-py3 as full

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt update \
    && apt install -y --no-install-recommends libre2-5 libb64-0d

COPY paddle-lib/paddle /opt/paddle
COPY build/libtriton_paddle.so /opt/tritonserver/backends/paddle/

ENV LD_LIBRARY_PATH="/opt/paddle/lib:$LD_LIBRARY_PATH"
```
<img width="776" alt="paddle_backend" src="https://user-images.githubusercontent.com/14275056/126733570-6aa0d598-d234-4ac1-b803-6241d79c20d9.png">

BTW, you should try tritonserver:21.04. paddlepaddle backend was tested on 21.04

**Comment by zlsh80826** [comment]
BTW, you should try tritonserver:21.04. paddlepaddle backend was tested on 21.04

**Comment by Aun0124** [comment]
@zlsh80826  I think perhaps is my cuda or driver version problem as I get error as below, i'll try update it and see how.

![image](https://user-images.githubusercontent.com/44689330/126735677-3c44b30b-c993-473f-a76e-5be0b70a5d43.png)

![image](https://user-images.githubusercontent.com/44689330/126735663-51ed4eea-94d8-4c90-a3a5-6ce0a846978e.png)
