### ISSUE TITLE
bash build_paddle.sh fails

### ISSUE THREAD

**Issue by bdeng3** [triton-inference-server/paddlepaddle_backend#8]
Hey team, 

I'm trying to build on MAC OS Monterey Version 12.5, but it fails with this message:

 2261.4 Scanning dependencies of target strided_slice_grad_kernel_base
 2261.5 [ 13%] Building CXX object paddle/phi/kernels/CMakeFiles/strided_slice_grad_kernel_base.dir/cpu/strided_slice_grad_kernel.cc.o
 2271.4 [ 13%] Linking CXX static library libtemporal_shift_grad_kernel.a
 2271.5 [ 13%] Built target temporal_shift_grad_kernel
 2271.5 [ 13%] Building CUDA object paddle/phi/kernels/CMakeFiles/strided_slice_grad_kernel_base.dir/gpu/strided_slice_grad_kernel.cu.o
 2292.2 /tmp/nvcc-lazy-build.KEVGwZ3b/build.sh.pre: line 18: 56852 Killed                  cicc --c++14 --gnu_version=90300 -w --orig_src_file_name "/opt/tritonserver/Paddle/paddle/phi/kernels/gpu/strided_slice_grad_kernel.cu" --allow_managed --extended-lambda --relaxed_constexpr -arch compute_86 -m64 --no-version-ident -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 --include_file_name "strided_slice_grad_kernel.fatbin.c" -tused --gen_module_id_file --module_id_file_name "/tmp/nvcc-lazy-build.KEVGwZ3b/strided_slice_grad_kernel.module_id" --gen_c_file_name "/tmp/nvcc-lazy-build.KEVGwZ3b/strided_slice_grad_kernel.compute_86.cudafe1.c" --stub_file_name "/tmp/nvcc-lazy-build.KEVGwZ3b/strided_slice_grad_kernel.compute_86.cudafe1.stub.c" --gen_device_file_name "/tmp/nvcc-lazy-build.KEVGwZ3b/strided_slice_grad_kernel.compute_86.cudafe1.gpu" "/tmp/nvcc-lazy-build.KEVGwZ3b/strided_slice_grad_kernel.compute_86.cpp1.ii" -o "/tmp/nvcc-lazy-build.KEVGwZ3b/strided_slice_grad_kernel.compute_86.ptx"
 2292.2 make[2]: *** [paddle/phi/kernels/CMakeFiles/strided_slice_grad_kernel_base.dir/build.make:76: paddle/phi/kernels/CMakeFiles/strided_slice_grad_kernel_base.dir/gpu/strided_slice_grad_kernel.cu.o] Error 137
 2292.2 make[2]: *** Waiting for unfinished jobs....
 2293.2 Scanning dependencies of target stack_grad_kernel
 2293.2 [ 13%] Building CXX object paddle/phi/kernels/CMakeFiles/stack_grad_kernel.dir/cpu/stack_grad_kernel.cc.o
 2294.5 [ 13%] Building CUDA object paddle/phi/kernels/CMakeFiles/strided_slice_kernel_base.dir/gpu/strided_slice_kernel.cu.o
 2301.4 make[1]: *** [CMakeFiles/Makefile2:16722: paddle/phi/kernels/CMakeFiles/strided_slice_grad_kernel_base.dir/all] Error 2
 2301.4 make[1]: *** Waiting for unfinished jobs....
 2301.4 [ 13%] Building CUDA object paddle/phi/kernels/CMakeFiles/stack_grad_kernel.dir/gpu/stack_grad_kernel.cu.o
 2319.8 [ 13%] Linking CXX static library libtile_kernel.a
 2319.9 [ 13%] Built target tile_kernel
 2320.0 [ 13%] Linking CXX static library libtop_k_grad_kernel.a
 2320.1 [ 13%] Built target top_k_grad_kernel
 2339.7 [ 13%] Linking CXX static library libdropout_grad_kernel.a
 2339.8 [ 13%] Built target dropout_grad_kernel
 2344.6 [ 13%] Linking CXX static library libstack_grad_kernel.a
 2344.6 [ 13%] Built target stack_grad_kernel
 2394.0 [ 13%] Linking CXX static library libtrace_kernel.a
 2394.1 [ 13%] Built target trace_kernel
 2448.2 [ 13%] Linking CXX static library libstrided_slice_kernel_base.a
 2448.3 [ 13%] Built target strided_slice_kernel_base
 2479.7 [ 13%] Linking CXX static library libtranspose_kernel.a
 2479.8 [ 13%] Built target transpose_kernel
 2479.9 make: *** [Makefile:130: all] Error 2
------
executor failed running [/bin/sh -c python3 -m pip install pyyaml && mkdir build-env &&     cd build-env &&     cmake .. -DWITH_PYTHON=OFF              -DWITH_GPU=ON              -DWITH_TESTING=OFF              -DWITH_INFERENCE_API_TEST=OFF              -DCMAKE_BUILD_TYPE=Release              -DCUDA_ARCH_NAME=Auto              -DON_INFER=ON              -DWITH_MKL=ON              -DWITH_TENSORRT=ON              -DWITH_ONNXRUNTIME=ON              -DCMAKE_C_COMPILER=`which gcc-8` -DCMAKE_CXX_COMPILER=`which g++-8` &&     make -j`nproc`]: exit code: 2

It seems to me the "cmake" command cause the problem, any idea on how to fix this?

**Comment by heliqi** [comment]
I'm sorry we didn't test and support it on Mac OS.
Usually Mac OS does not have  GPU, you can try to modify the cmake instruction:
```
RUN python3 -m pip install pyyaml && mkdir build-env && \
    cd build-env && \
    cmake .. -DWITH_PYTHON=OFF \
             -DWITH_GPU=OFF \
             -DWITH_TESTING=OFF \
             -DWITH_INFERENCE_API_TEST=OFF \
             -DCMAKE_BUILD_TYPE=Release \
             -DCUDA_ARCH_NAME=Auto \
             -DON_INFER=ON \
             -DWITH_MKL=ON \
             -DWITH_TENSORRT=OFF \
             -DWITH_ONNXRUNTIME=ON \
             -DCMAKE_C_COMPILER=`which gcc-8` -DCMAKE_CXX_COMPILER=`which g++-8` && \
```

**Comment by bdeng3** [comment]
@heliqi no worry, thanks for the prompt reply! 

I tried setting "DWITH_GPU=OFF" and the build finished successfully! Cheers!

However when I tried the next step: 

`$ bash scripts/build_paddle_backend.sh`

It fails with 

(paddle_env) user@user-MBP paddlepaddle_backend % bash scripts/launch_triton_server.sh
+ docker build -t tritonserver-paddle .
[+] Building 52.7s (4/4) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                           0.0s
 => => transferring dockerfile: 3.50kB                                                                                                                                                                         0.0s
 => [internal] load .dockerignore                                                                                                                                                                              0.0s
 => => transferring context: 2B                                                                                                                                                                                0.0s
 => ERROR [internal] load metadata for nvcr.io/nvidia/tritonserver:21.10-py3-min                                                                                                                              52.4s
 => ERROR [internal] load metadata for nvcr.io/nvidia/tritonserver:21.10-py3                                                                                                                                  52.6s
------
 > [internal] load metadata for nvcr.io/nvidia/tritonserver:21.10-py3-min:
------
------
 > [internal] load metadata for nvcr.io/nvidia/tritonserver:21.10-py3:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to authorize: rpc error: code = Unknown desc = failed to fetch anonymous token: unexpected status: 401 Unauthorized

It seems to have something to do with nvidia again. Should I modify the `build_paddle_backend.sh` script to ignore GPU accordingly?

**Comment by heliqi** [comment]
@bdeng3  Yes!
Error running 'bash scripts/launch_triton_server.sh'  script, or  'bash scripts/build_paddle_backend.sh' script?

**Example:**
https://github.com/triton-inference-server/paddlepaddle_backend/blob/a27ff0ccb49edc2b2dc72612d69a037247c0d657/Dockerfile#L46  .It needs to be modified back to:
```
&& python3 -m pip install paddlepaddle paddlenlp faster_tokenizer
```

The `launch_triton_server.sh` script has GPU parameters: 
```
delet  '--gpus=all'
```

**Comment by heliqi** [comment]
@bdeng3 
Could you please describe your requirements and usage scenarios? 
I can compile a Mac OS image for you, but it's worth noting that we haven't done all the build tests yet.

If you have good usage needs, it may be faster for me to compile the image and upload it to Docker Hub.

This is the GPU image we provide based on Triton 21.10:
```
docker pull paddlepaddle/triton_paddle:21.10
```

**Comment by bdeng3** [comment]
@heliqi Thank you for the detailed explanation! 

Sure. I need to deploy the open-source PaddleOCR models to the triton server. Specifically, the `en_PP-OCRv3_det_infer`, `ch_ppocr_mobile_v2.0_cls_infer` and `en_PP-OCRv3_rec_infer` models provided [here](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/ppocr_introduction_en.md#pp-ocr-series-model-listupdate-on-20220428). 

I'm very new to triton so I'm not exactly sure how to do it. I tried a couple of ways:

1. Convert those models from `pdmodel` format into ONNX and pull a docker image of Triton inference server from [here](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tritonserver/tags). This seems to be the most straightforward way, but I got the following errors when I did `docker run ...`. My assumption is I didn't write the `config.pbtxt` correctly for those models.
![image](https://user-images.githubusercontent.com/89899604/186563081-b401a0fd-64cc-4bf5-9237-e3d35dd6a188.png)

2. Another way I've tried is trying to build the Paddle Backend in this repo by following the README instructions. 

Even now I'm not sure which way is the best approach to solve this problem. Both seem legit to me. It would be great if you could share some high-level suggestions on how to deploy a paddle model to Triton server. Thank you!!

**Comment by heliqi** [comment]
Are you deploying the model on Mac OS, not Linux?  
Currently Paddle only provides a way to start the Triton service based on Docker. You can try pulling the image and starting the service:
```
# pull image
docker pull paddlepaddle/triton_paddle:21.10

# run docker (The directory to which the disk is mounted needs to be modified)
ocker run -it   --net=host --name paddle_triton --rm  -v  /path/to/models :models   paddlepaddle/triton_paddle:21.10 bash

# start service
/opt/tritonserver/bin/tritonserver  --model-repository=models
```

**Comment by heliqi** [comment]
Documentation for Triton and Paddle Backend:
[Triton model repository](https://github.com/triton-inference-server/server/blob/main/docs/model_repository.md)
[Triton model configuration](https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md)
[Paddle model configuration](https://github.com/triton-inference-server/paddlepaddle_backend/blob/main/docs/model_configuration.md)

If use Paddle Backend, the model names in the edition subdirectories under the Models directory must be `model.pdmodel`and `model.pdiparams`. 

Model Repository Example:
```
models
  └── ResNet50
      ├── 1
      │   ├── model.pdiparams
      │   └── model.pdmodel
      └── config.pbtxt
```

Model Configuration  Example:
```
name: "ResNet50-v1.5"
backend: "paddle"
max_batch_size: 64

input [
  {
    name: "x0"
    data_type: TYPE_FP32
    dims: [ 3, 224, 224 ]
  }
]

output [
  {
    name: "save_infer_model/scale_0.tmp_1"
    data_type: TYPE_FP32
    dims: [ 1000 ]
  }
]

instance_group [ 
  { 
    count: 1
    kind: KIND_GPU
    gpus: [0]
  }
]

```

**Comment by bdeng3** [comment]
Eventually we'll deploy to model on a Linux server, but currently I'm trying it out locally just to see how things work. 

Sure. I'll try what you recommended (paddle backend) and let you know how things go. Just curious, are you recommending against converting the model into ONNX and deploying it?

**Comment by heliqi** [comment]
Since Mac OS is not very friendly to using Docker, I suggest you try it directly on a LInux server.
I recommend using Paddle Backend directly unless you do not meet your requirements. Converting to ONNX format can introduce other errors, such as conversion failure, precision misalignment, and so on...

**Comment by heliqi** [comment]
@bdeng3  If `Paddle Backend` does not meet the requirements, you can convert the model to ONNX format using `Paddle2onnx`, then use `ONNXRuntime Backend`.

**Comment by bdeng3** [comment]
> /opt/tritonserver/bin/tritonserver  --model-repository=models

When I run the command above, I can see the ONNX backend is being initialized. I made sure `backend: "paddle"` is set in the model configuration file. I also tried restarting the docker and running again, but that doesn't help either. 

I attached the output below:

![image](https://user-images.githubusercontent.com/89899604/186612837-26b3cb29-fa62-4339-877d-2e1921397403.png)

**Comment by heliqi** [comment]
<img width="819" alt="05c437a245b1018b09de7ef45ca7f530" src="https://user-images.githubusercontent.com/34152981/186616891-b1b37547-3a69-48b8-a969-5c9fa87f89b0.png">
@bdeng3 
use *nvidia-smi* and check whether the driver version matches. 

The Triton image requires the driver version:  [Nvidia Docs](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html)
```
Release 21.10 is based on [NVIDIA CUDA 11.4.2](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html) with [cuBLAS 11.6.5.2](https://docs.nvidia.com/cuda/cublas/index.html), which requires [NVIDIA Driver](http://www.nvidia.com/Download/index.aspx?lang=en-us) release 470 or later. 

However, if you are running on Data Center GPUs (formerly Tesla), for example, T4, you may use NVIDIA driver release 418.40 (or later R418), 440.33 (or later R440), 450.51 (or later R450), or 460.27 (or later R460).

The CUDA driver's compatibility package only supports particular drivers. [3](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html#fnsrc_3)
```

Also send me the content of config.pbtxt file in models

**Comment by bdeng3** [comment]
For some reason, I'd have to stick with trying it out locally on my Mac, so I don't really have GPU for our experiments🙁. 

I checked [this page](https://github.com/triton-inference-server/server/blob/main/docs/build.md#cpu-only-build), and it seems the current CPU-Only Build doesn't have Paddle backend? If this is true, I'm afraid I'd have to go back to the ONNX approach because the actual server we'll be using only has CPU inference for now. 


Attached the config.pbtxt file below: 

===================================
name: "ch_ppocr_mobile_v2.0_cls_infer"
platform: "paddle"
max_batch_size : 1
input [
  {
    name: "data_0"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 32, 100 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ -1, 2 ]
  }
]

===================================
name: "en_PP-OCRv3_det_infer"
platform: "paddle"
max_batch_size : 1
input [
  {
    name: "data_0"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 960, 960 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ -1, 1, 960, 960 ]
  }
]


===================================
name: "en_PP-OCRv3_rec_infer"
platform: "paddle"
max_batch_size : 1
input [
  {
    name: "data_0"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [3, 48, -1]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ -1, -1, 97 ]
  }
]

**Comment by heliqi** [comment]
@bdeng3 
"platform"  must be changed to "backend". 

Pay attention to this example:
```
name: "ResNet50-v1.5"
backend: "paddle"
max_batch_size: 64

input [
  {
    name: "x0"
    data_type: TYPE_FP32
    dims: [ 3, 224, 224 ]
  }
]

output [
  {
    name: "save_infer_model/scale_0.tmp_1"
    data_type: TYPE_FP32
    dims: [ 1000 ]
  }
]

instance_group [ 
  { 
    count: 1
    kind: KIND_CPU
  }
]
```

**Comment by bdeng3** [comment]
My bad! after changing "platform" to "backend", it seems to be working! I'll do more experiments and see if everything works as expected! Great thanks for your support!!

![image](https://user-images.githubusercontent.com/89899604/186850382-07fb5aa1-98d5-463e-b75a-1241cf46a0b0.png)

**Comment by bdeng3** [comment]
However when I ran `curl -v localhost:8000/v2/health/ready` as suggested [here](https://github.com/triton-inference-server/paddlepaddle_backend#verify-triton-is-running-correctly) to verify triton is running smoothly, Connection refused. 

<img width="627" alt="image" src="https://user-images.githubusercontent.com/89899604/186851682-d4817797-70c0-4d28-a74c-e90ad60c90ce.png">

Is this expected since we do not exactly follow the steps in the README? I'll follow the examples in the repo to see how can we send images to triton server and get the results

**Comment by heliqi** [comment]
@bdeng3  Check your client and be sure to close the proxy.
